# Shown by GitHub as a "Sponsor" button on the repository page.
# Commercial use of SCRIPTUM is free; this is the voluntary support asked for
# in section 6 of LICENSES/Commercial.de.md.
#
github: PyTomE
ko_fi: embilaco
